container:
  image: python:slim

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  run_script: python -u subscribe/collect.py --all --overwrite --skip
  uplod_yanl: python -u subscribe/merged2upload.py ${Token}
